// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtY8wsCp_j5aQ_Fg3PEP-CCeZmldqVyYE',
    appId: '1:416735504958:web:c590b1c0fc4f1dc2833f6f',
    messagingSenderId: '416735504958',
    projectId: 'sistema-abastecimento-eca99',
    authDomain: 'sistema-abastecimento-eca99.firebaseapp.com',
    databaseURL: 'https://sistema-abastecimento-eca99-default-rtdb.firebaseio.com',
    storageBucket: 'sistema-abastecimento-eca99.firebasestorage.app',
    measurementId: 'G-86MPS2XEMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWc377hSJCln5Q6nEHEGciCnaoMLrlcTs',
    appId: '1:416735504958:android:c6daeb3c158188a1833f6f',
    messagingSenderId: '416735504958',
    projectId: 'sistema-abastecimento-eca99',
    databaseURL: 'https://sistema-abastecimento-eca99-default-rtdb.firebaseio.com',
    storageBucket: 'sistema-abastecimento-eca99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAtaNg4-st4xRtl3AdeuXayFkyGMAwJEA',
    appId: '1:416735504958:ios:489091b38eb565b1833f6f',
    messagingSenderId: '416735504958',
    projectId: 'sistema-abastecimento-eca99',
    databaseURL: 'https://sistema-abastecimento-eca99-default-rtdb.firebaseio.com',
    storageBucket: 'sistema-abastecimento-eca99.firebasestorage.app',
    iosBundleId: 'com.example.provap2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAtaNg4-st4xRtl3AdeuXayFkyGMAwJEA',
    appId: '1:416735504958:ios:489091b38eb565b1833f6f',
    messagingSenderId: '416735504958',
    projectId: 'sistema-abastecimento-eca99',
    databaseURL: 'https://sistema-abastecimento-eca99-default-rtdb.firebaseio.com',
    storageBucket: 'sistema-abastecimento-eca99.firebasestorage.app',
    iosBundleId: 'com.example.provap2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtY8wsCp_j5aQ_Fg3PEP-CCeZmldqVyYE',
    appId: '1:416735504958:web:0fa28faa336cead0833f6f',
    messagingSenderId: '416735504958',
    projectId: 'sistema-abastecimento-eca99',
    authDomain: 'sistema-abastecimento-eca99.firebaseapp.com',
    databaseURL: 'https://sistema-abastecimento-eca99-default-rtdb.firebaseio.com',
    storageBucket: 'sistema-abastecimento-eca99.firebasestorage.app',
    measurementId: 'G-737RPHQPV1',
  );

}